import { useEffect, useState } from "react";
import api from "../api/axios.js";
import DashboardLayout from "../components/DashboardLayout.jsx";

const dayOrder = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

const MealCard = ({ label, meal }) =>
  meal ? (
    <div className="interactive-card bg-white/5 rounded-lg p-4 border border-transparent">
      <p className="text-slate-400 text-xs uppercase tracking-wide mb-1">
        {label}
      </p>
      <p className="text-white font-medium">{meal.name}</p>
      <p className="text-slate-400 text-sm mt-1">
        {meal.calories} kcal &middot; {meal.protein}g protein
      </p>
    </div>
  ) : null;

const Dashboard = () => {
  const [plan, setPlan] = useState(null);
  const [activeDay, setActiveDay] = useState("Monday");
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  const loadPlan = async () => {
    setLoading(true);
    try {
      const res = await api.get("/plans/latest");
      setPlan(res.data);
    } catch (err) {
      setPlan(null); // no plan yet, that's fine
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPlan();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    try {
      const res = await api.post("/plans/generate");
      setPlan(res.data);
      setActiveDay("Monday");
    } catch (err) {
      setError(
        err.response?.data?.message ||
          "Couldn't generate your plan. Please try again."
      );
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return (
      <DashboardLayout>
        <p className="text-slate-400">Loading your dashboard...</p>
      </DashboardLayout>
    );
  }

  const activeDayData = plan?.days?.find((d) => d.day === activeDay);

  return (
    <DashboardLayout>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-white">
            Your 7-Day Plan
          </h2>
          <p className="text-slate-400 text-sm">
            Generated by AI based on your profile
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="btn-primary px-5 py-2 rounded-full text-sm disabled:opacity-50"
        >
          {generating
            ? "Generating..."
            : plan
            ? "🔄 Regenerate Plan"
            : "✨ Generate My Plan"}
        </button>
      </div>

      {error && (
        <p className="text-red-400 text-sm mb-6 bg-red-500/10 p-3 rounded-lg">
          {error}
        </p>
      )}

      {!plan && !generating && (
        <div className="bg-white/5 rounded-2xl p-10 text-center">
          <p className="text-slate-300 mb-4">
            You don't have a plan yet. Click "Generate My Plan" above and the
            AI will build a full 7-day workout and meal plan from the details
            you gave during onboarding.
          </p>
        </div>
      )}

      {generating && (
        <div className="bg-white/5 rounded-2xl p-10 text-center">
          <p className="text-slate-300">
            🧠 Your AI coach is building your plan... this can take 10-20
            seconds.
          </p>
        </div>
      )}

      {plan && (
        <>
          {/* Day tabs */}
          <div className="flex gap-2 mb-6 flex-wrap">
            {dayOrder.map((day) => {
              const dayData = plan.days.find((d) => d.day === day);
              return (
                <button
                  key={day}
                  onClick={() => setActiveDay(day)}
                  className={`px-4 py-2 rounded-full text-sm font-medium border-2 transition ${
                    activeDay === day
                      ? "border-primary bg-primary/20 text-white"
                      : "border-white/10 bg-white/5 text-slate-300 hover:border-white/30"
                  } ${dayData?.isRestDay ? "opacity-70" : ""}`}
                >
                  {day.slice(0, 3)}
                  {dayData?.isRestDay && " 💤"}
                </button>
              );
            })}
          </div>

          {activeDayData && (
            <div className="grid md:grid-cols-2 gap-6">
              {/* Workout */}
              <div className="bg-dark-card border border-white/10 rounded-2xl p-6">
                <h3 className="text-white font-semibold text-lg mb-1">
                  🏋️ Workout
                </h3>
                {activeDayData.isRestDay ? (
                  <p className="text-slate-400 mt-3">
                    Rest day — recovery time. Light stretching or a walk is
                    great here.
                  </p>
                ) : (
                  <>
                    <p className="text-primary text-sm mb-4">
                      {activeDayData.workout?.focus}
                    </p>
                    <div className="flex flex-col gap-3">
                      {activeDayData.workout?.exercises?.map((ex, i) => (
                        <div
                          key={i}
                          className="interactive-card flex justify-between items-center bg-white/5 rounded-lg px-4 py-3 border border-transparent"
                        >
                          <div>
                            <p className="text-white text-sm font-medium">
                              {ex.name}
                            </p>
                            <p className="text-slate-400 text-xs">
                              {ex.muscleGroup}
                            </p>
                          </div>
                          <p className="text-slate-300 text-sm">
                            {ex.sets} x {ex.reps}
                          </p>
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </div>

              {/* Meals */}
              <div className="bg-dark-card border border-white/10 rounded-2xl p-6">
                <h3 className="text-white font-semibold text-lg mb-1">
                  🍽️ Meals
                </h3>
                <p className="text-primary text-sm mb-4">
                  {activeDayData.totalCalories} kcal &middot;{" "}
                  {activeDayData.totalProtein}g protein
                </p>
                <div className="flex flex-col gap-3">
                  <MealCard label="Breakfast" meal={activeDayData.meals?.breakfast} />
                  <MealCard label="Lunch" meal={activeDayData.meals?.lunch} />
                  <MealCard label="Dinner" meal={activeDayData.meals?.dinner} />
                  {activeDayData.meals?.snacks?.map((s, i) => (
                    <MealCard key={i} label="Snack" meal={s} />
                  ))}
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </DashboardLayout>
  );
};

export default Dashboard;
